### ISSUE TITLE
chrome 打不开你的blog

### ISSUE THREAD

**Issue by Arthur-Shi** [yzy1996/yzy1996.github.io#1]

**Comment by yzy1996** [comment]
我可以打开呀，或者你试试crazyang.top  一起研究解决一下

**Comment by yzy1996** [comment]
> _No description provided._

请问你在重试或者刷新网页后可以正常访问吗

**Comment by Arthur-Shi** [comment]
访问进去 打不开具体的blog

出现的是



We didn't receive a proper request from your browser.

Sorry about that. Please try refreshing and contact us if the problem persists.

Contact Support — GitHub Status — @githubstatus

**Comment by Arthur-Shi** [comment]
... 针对我吗？ 是因为我电脑用的vpn？

**Comment by Arthur-Shi** [comment]
没错， 我是linux 在network 设置的指点地址，所以 连不上 我关了 就连上了。

**Comment by yzy1996** [comment]
好吧
